### ISSUE TITLE
Adding Help Popups to Each Tab

### ISSUE THREAD

**Issue by kdaust** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#16]
@meztez would appreciate your advice on how to best set this up. We would like to have an overall help page which would always be available on the CCISS header, and then would like to have a separate help page for each tab. Will's suggestion was to have a little question mark symbol after the name of each tab in the header which people could click, but I wasn't sure how to do this in the flexdashboard environment. I think other suggestions would also be fine. 

Currently, I set up the main help popup to read from a separate RMarkdown documents and render as html in a modal. Do you think this is a good strategy, or would it be better for each help tab to be a separate section in the Index.Rmd?
Thank you!!

**Comment by meztez** [comment]
@kdaust I would probably make a link out of the question mark to goes to your specific tab help page in the about a tab.

Overlay popup require css, js and have horrible UI experience on mobile. Since they don't take up the whole screen, you get less real estate to display content. Most of the time, you have to chase down a button to return to the tab you were browsing before that. Popups are good for tooltips about the size of a tweet.

**Comment by kdaust** [comment]
@meztez one more thing related to this that would be awesome if you could do - those question marks are great, and it would be nice to have one after each tab name (e.g. select sites, feasibility report, etc), where clicking on one will take you to that section in the Instructions page (currently it doesn't have sections for that but you could just put some headings in). I'm sure I could figure out how to do it but given you've set it all up it would probably be easier for you. Thanks!

**Comment by kdaust** [comment]
Looks fantastic! Thanks :)
